(ns common-crawl.classify
  "Domain extraction and topic classification — the decision half of
  `rust/cc-phase3/src/main.rs`.

  ADR-2607072000 says implementations that would reach for Rust are written in
  `.cljc` here. `cc-phase3` is a WAT→Parquet pipeline, and most of it really is
  mechanism: rayon fan-out, gzip streaming, Arrow/Parquet writers. But
  `classify_topic` and `extract_domain` are neither — they are a table of rules
  and a string scan, i.e. exactly the part that decides what the corpus SAYS
  about a page. That part belongs here, the way `common-crawl.did` already
  holds the DID derivation the same file mirrors.

  SSoT INVARIANT, same shape as `common-crawl.did`'s:
    `classify-topic` / `extract-domain` here and `classify_topic` /
    `extract_domain` in rust/cc-phase3/src/main.rs MUST agree. Change one,
    change both, and extend classify_test.cljc — whose expectations were
    generated by RUNNING the Rust, not by reading it (see that file).

  Pure functions only: no I/O, no parquet, no parallelism."
  (:require [clojure.string :as str]))

;; ── domain ──────────────────────────────────────────────────────────────────

(defn extract-domain
  "Hostname from a URL, lower-cased, port stripped. nil when there is no host.

  Deliberately NOT a URL parser: the Rust finds `://`, takes up to the next
  `/`, and strips a trailing `:port` unless the authority contains `[` (an
  IPv6 literal, whose colons are not a port separator). Anything a real parser
  would additionally normalise — userinfo, IDN, trailing dot — is left alone,
  because the corpus keys on this string and normalising it here would silently
  re-key rows the Rust already wrote."
  [url]
  (when (string? url)
    (let [i (str/index-of url "://")]
      (when i
        (let [rest (subs url (+ i 3))
              host-end (or (str/index-of rest "/") (count rest))
              host-port (subs rest 0 host-end)
              colon (str/last-index-of host-port ":")
              host (if (and colon (not (str/includes? host-port "[")))
                     (subs host-port 0 colon)
                     host-port)]
          (when-not (= "" host)
            (str/lower-case host)))))))

;; ── topic ───────────────────────────────────────────────────────────────────

(def rules
  "Ordered classification rules — the Rust's `RULES` array as data.

  Order is significant: the first rule that matches wins, so a `.gov` domain is
  `government` even though its title may also contain `research`. Keeping them
  as data rather than as a `cond` means the table can be read, counted and
  tested as a value.

  A `:tld` entry is matched with `includes?`, not `ends-with?`. That is what the
  Rust does (`dl.ends_with(tld) || dl.contains(tld)`, where the second subsumes
  the first) and it has consequences worth stating rather than discovering:
  `.io` matches `alaska.iowa-example.com`. Preserved deliberately — the corpus
  was labelled with these semantics."
  [{:slug "government"
    :tlds [".gov" ".go.jp" ".gc.ca" ".gov.uk" ".gov.au" ".europa.eu"]
    :keywords ["government" "ministry"]}
   {:slug "legal" :tlds [".courts"] :keywords ["court" "law" "legal"]}
   {:slug "academic" :tlds [".edu" ".ac.jp" ".ac.uk"]
    :keywords ["university" "research" "journal"]}
   {:slug "science" :tlds []
    :keywords ["science" "biology" "physics" "chemistry" "genome" "ncbi" "pubmed"]}
   {:slug "technology" :tlds [".io" ".dev"]
    :keywords ["github" "stackoverflow" "developer" "api" "sdk"]}
   {:slug "news_media" :tlds [] :keywords ["news" "times" "post" "herald"]}
   {:slug "health" :tlds []
    :keywords ["health" "medical" "hospital" "pharma" "who.int"]}
   {:slug "commerce" :tlds [".shop" ".store"]
    :keywords ["shop" "buy" "price" "amazon" "ebay"]}
   {:slug "finance" :tlds [".bank"]
    :keywords ["bank" "finance" "invest" "stock" "insurance"]}
   {:slug "security" :tlds []
    :keywords ["security" "cve" "malware" "threat" "vulnerability" "cyber"]}
   {:slug "culture" :tlds [".museum"]
    :keywords ["museum" "art" "culture" "heritage"]}
   {:slug "education" :tlds [] :keywords ["learn" "course" "tutorial" "education"]}
   {:slug "infrastructure" :tlds []
    :keywords ["transport" "railway" "energy" "telecom"]}
   {:slug "jp_classics" :tlds [".aozora.gr.jp"] :keywords []}])

(def reference-domains
  "Checked before `rules` and returning immediately, so a Wikipedia article
  about a court case is `reference`, not `legal`."
  ["wikipedia.org" "wikimedia.org" "wikidata.org" "wiktionary.org"])

(defn- rule-matches? [{:keys [tlds keywords]} dl tl]
  (or (boolean (some #(str/includes? dl %) tlds))
      ;; a keyword hits on EITHER the domain or the title
      (boolean (some #(or (str/includes? dl %) (str/includes? tl %)) keywords))))

(defn classify-topic
  "Topic slug for a page, or \"\" when nothing matches.

  Empty string rather than nil: the Rust returns `&'static str` and the parquet
  column is non-null, so a nil here would become the string \"null\" or a schema
  error downstream depending on the writer."
  [domain title]
  (let [dl (str/lower-case (or domain ""))
        tl (str/lower-case (or title ""))]
    (cond
      (some #(str/includes? dl %) reference-domains) "reference"
      (str/includes? dl "openstreetmap.org") "infrastructure"
      :else (or (:slug (first (filter #(rule-matches? % dl tl) rules))) ""))))

(defn- quoted-after
  "The text between the next pair of quotes following `marker`, or nil."
  [s marker]
  (when-let [i (clojure.string/index-of s marker)]
    (let [rest (subs s (+ i (count marker)))]
      (when-let [e (clojure.string/index-of rest "\"")]
        (subs rest 0 e)))))

(defn parse-domain-line
  "`MERGE (d:DomainDID {did: \"X\"}) ON CREATE SET d.domain = \"Y\", d.slug = \"Z\"`
  -> {:did :domain :slug}, or nil.

  The decision inside `rust/cc-domain-extract`. That binary stays: its whole
  reason for existing is throughput over a directory of batch files
  (~200-500 files/s against Python's ~11), and rayon fan-out plus gzip output
  is mechanism, not a decision. What IS a decision is which lines count and
  which three fields they yield — so that lives here, and the Rust's copy has
  something to be checked against.

  Deliberately not a regex, matching the Rust: these lines are generated by
  this pipeline, and a scanner that finds literal markers cannot be surprised
  by a quote inside a value the way a greedy pattern can."
  [line]
  (when (string? line)
    (let [marker "MERGE (d:DomainDID {did: \""]
      (when-let [i (clojure.string/index-of line marker)]
        (let [rest (subs line (+ i (count marker)))
              did-end (clojure.string/index-of rest "\"")]
          (when did-end
            (let [did (subs rest 0 did-end)
                  domain (quoted-after rest "d.domain = \"")
                  slug (quoted-after rest "d.slug = \"")]
              (when (and domain slug)
                {:did did :domain domain :slug slug}))))))))

(defn domain-did-from-slug
  "did:web for a domain slug — the vertex a page's DID hangs off."
  [domain-slug]
  (str "did:web:site.etzhayyim.com:" domain-slug))
