(ns common-crawl.classify-test
  "Parity with `rust/cc-phase3/src/main.rs`.

  Every expectation below was GENERATED BY RUNNING the Rust, not by reading it:
  `classify_topic` and `extract_domain` were lifted verbatim into a standalone
  binary (both use only std) and fed these inputs. That matters because two of
  the answers are surprising, and reading the source is exactly how you talk
  yourself out of a surprise:

    alaska.iowa-example.com  -> \"technology\"
      `.io` is matched with `contains`, not `ends_with`, so it hits inside
      `.iowa-`. Preserved on purpose — the corpus is already labelled this way.

    https://[2001:db8::1]:8080/p -> \"[2001:db8::1]:8080\"
      The IPv6 guard skips port-stripping entirely when the authority contains
      `[`, so a bracketed host KEEPS its port. Arguably wrong; not ours to
      change here, because rows are keyed on this string.

  Change the Rust, change this file, and regenerate rather than reason."
  (:require [clojure.test :refer [deftest is testing]]
            [common-crawl.classify :as classify]))

(def topic-cases
  ;; [domain title expected]
  [["en.wikipedia.org" "Court of Appeal" "reference"]
   ["commons.wikimedia.org" "" "reference"]
   ["EN.WIKIPEDIA.ORG" "Mixed Case" "reference"]
   ["www.openstreetmap.org" "Map" "infrastructure"]
   ["nsa.gov" "Government Portal" "government"]
   ;; first rule wins: .gov beats the academic keywords in the title
   ["research.gov" "university research journal" "government"]
   ["courts.example.com" "Docket" "legal"]
   ;; a keyword hits on the TITLE as well as the domain
   ["example.com" "Supreme Court Ruling" "legal"]
   ["mit.edu" "Research" "academic"]
   ["example.org" "pubmed central" "science"]
   ["kotoba.io" "home" "technology"]
   ["example.com" "GitHub mirror" "technology"]
   ["example.com" "Daily News" "news_media"]
   ["who.int" "Health" "health"]
   ["shop.example" "Buy now" "commerce"]
   ["first.bank" "Invest" "finance"]
   ["example.com" "CVE-2024-1234 advisory" "security"]
   ["louvre.museum" "Art" "culture"]
   ["example.com" "Tutorial: learn Clojure" "education"]
   ["example.com" "railway timetable" "infrastructure"]
   ["www.aozora.gr.jp" "" "jp_classics"]
   ;; no rule matches → empty string, never nil (the parquet column is non-null)
   ["example.com" "nothing here" ""]
   ["alaska.iowa-example.com" "nothing" "technology"]])

(def domain-cases
  ;; [url expected] — nil means the Rust returned None
  [["https://example.com/foo/bar" "example.com"]
   ["https://example.com:8443/x" "example.com"]
   ["http://Example.COM" "example.com"]
   ["https://[2001:db8::1]:8080/p" "[2001:db8::1]:8080"]
   ["https://[2001:db8::1]/p" "[2001:db8::1]"]
   ["ftp://files.example.com/a" "files.example.com"]
   ["not-a-url" nil]
   ["https:///emptyhost" nil]
   ["https://example.com" "example.com"]])

(deftest classify-topic-matches-the-rust
  (doseq [[domain title expected] topic-cases]
    (is (= expected (classify/classify-topic domain title))
        (str (pr-str domain) " / " (pr-str title)))))

(deftest extract-domain-matches-the-rust
  (doseq [[url expected] domain-cases]
    (is (= expected (classify/extract-domain url)) (pr-str url))))

(deftest classification-never-returns-nil
  (testing "the parquet column is non-null, so \"\" is the miss, not nil"
    (is (= "" (classify/classify-topic "example.com" "")))
    (is (= "" (classify/classify-topic nil nil)))))

(deftest rules-are-data-and-ordered
  (testing "the table is a value, so it can be counted and read"
    (is (= 14 (count classify/rules)))
    (is (= "government" (:slug (first classify/rules))))
    (is (= "jp_classics" (:slug (last classify/rules))))
    (testing "every rule can actually fire"
      (doseq [{:keys [slug tlds keywords]} classify/rules]
        (is (or (seq tlds) (seq keywords))
            (str slug " has no way to match"))))))

(deftest parse-domain-line-matches-the-rust
  (let [line (str "MERGE (d:DomainDID {did: \"did:web:site.etzhayyim.com:example-com\"}) "
                  "ON CREATE SET d.domain = \"example.com\", d.slug = \"example-com\"")]
    (is (= {:did "did:web:site.etzhayyim.com:example-com"
            :domain "example.com"
            :slug "example-com"}
           (classify/parse-domain-line line))))
  (testing "a line without the marker yields nothing"
    (is (nil? (classify/parse-domain-line "MERGE (p:Page {did: \"x\"})")))
    (is (nil? (classify/parse-domain-line "")))
    (is (nil? (classify/parse-domain-line nil))))
  (testing "a truncated line yields nothing rather than a partial record"
    (is (nil? (classify/parse-domain-line
               "MERGE (d:DomainDID {did: \"did:web:x\"}) ON CREATE SET d.domain = \"e.com\"")))))

(deftest domain-did-hangs-off-the-site
  (is (= "did:web:site.etzhayyim.com:example-com"
         (classify/domain-did-from-slug "example-com"))))
